[WIP] Map Management
AscEmu/AscEmu pull request #1011
Opened 2022-04-15 12:37 UTC by aaron02

**Description**
Cleanup files form MapManagement, Add Additional Files to Organize it better. Fix Static Creature and Gameobject Spawns, Fix random Transporter Crashes. Added Proper Instance Saves and Reset Times, Fixed AreaTrigger Messages, Added Support for Global Creature and Gameobject Respawns, 

The Changes are getting way to big now so i decided to make a PR.

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.
- [ ] Classic Support?
- [ ] Change Multithreading when more Crashes appear

**Tests Performed:** 
- [x] Build AE.
- [x] Server startup.
- [x] Log into world.

***Multiversion Ingame Tests Performed:***
- [x] BC
- [x] WotLK
- [x] Cata

2022-04-15 20:07 UTC, schnek requested changes

2022-04-15 20:21 UTC, schnek commented
MapDifficulty.dbc >= wotlk (but observed in TBC storage) https://wowdev.wiki/DB/MapDifficulty

2022-04-18 12:15 UTC, schnek commented
![image](https://user-images.githubusercontent.com/1216225/163806761-22a27964-ce4f-48e4-a34c-1df9205ae2cb.png)
after the first player enters the dungeon, the whole game world crashes 🤔

2022-04-18 13:26 UTC, aaron02 commented
thats the script that bugs at bt

2022-04-18 14:27 UTC, schnek commented
> thats the script that bugs at bt i have to reseach if bt also crashes at develop
> edit:
> this crash also occours on current develop because of an old unstable script, this is not a part of this pr ;)

it happens on wotlk😅 , which dungeon to check (except BlackTemple)


😁

2022-04-18 22:10 UTC, schnek commented on src/world/Map/Maps/InstanceMap.cpp
> +    if (InstancePlayerBind* playerBind = player->getBoundInstance(getBaseMap()->getMapId(), getDifficulty()))
{
more than 1 line
}

2022-04-19 09:35 UTC, Appled commented
> > thats the script that bugs at bt i have to reseach if bt also crashes at develop
> > edit:
> > this crash also occours on current develop because of an old unstable script, this is not a part of this pr ;)
> 
> it happens on wotlk😅 , which dungeon to check (except BlackTemple)

The crash happens only in Black Temple because the instance script for Black Temple is unstable

2022-04-19 12:26 UTC, schnek commented
> > > thats the script that bugs at bt i have to reseach if bt also crashes at develop
> > > edit:
> > > this crash also occours on current develop because of an old unstable script, this is not a part of this pr ;)
> > 
> > 
> > it happens on wotlk😅 , which dungeon to check (except BlackTemple)
> 
> The crash happens only in Black Temple because the instance script for Black Temple is unstable

i checked in sunwell plateau it works

2022-04-19 14:38 UTC, schnek approved these changes

2022-04-19 21:45 UTC, schnek commented
with transport (airship) a crash occurs, but the transport continues to work. the core falls.

stopping point
![image](https://user-images.githubusercontent.com/1216225/164106948-3536668a-c50d-4f38-9d23-a39845c70cbd.png)

2022-04-19 22:10 UTC, Appled commented
> 

when does it crash? how to reproduce?

2022-04-19 22:29 UTC, schnek commented
two test locations
https://www.youtube.com/watch?v=kNHyaK8z5e0&ab_channel=GosuNoob 
new character move to the airship. as well as a previously created character

![image](https://user-images.githubusercontent.com/1216225/164111641-20a255d3-6a00-44ca-bdf5-71aaa0aa1e4d.png)
![image](https://user-images.githubusercontent.com/1216225/164111129-ae47765a-4ceb-4e69-8bee-94046818c4d3.png)

2022-04-19 22:49 UTC, schnek commented
sometimes 1/2 route takes a long time to load, but successfully

2022-04-19 23:13 UTC, schnek commented
> when does it crash? how to reproduce?

sometimes 1/2 route takes a long time to load, but successfully


when exiting the client
![image](https://user-images.githubusercontent.com/1216225/164116098-37395380-f95c-41e6-b6f7-1299d53ed792.png)

2022-04-25 22:11 UTC, Appled commented
> ![image](https://user-images.githubusercontent.com/1216225/165174478-953c8720-b8dc-46f0-9a94-9322546b25f8.png) if don't plan on using it

Yeah I forgot to remove those 😄

2022-04-28 11:25 UTC, schnek commented
![image](https://user-images.githubusercontent.com/1216225/165741677-e83c24c3-ad08-43e5-860a-b294b6de11a8.png)
crash on start (vs2022)

2022-04-28 11:35 UTC, Appled commented
I can't reproduce

2022-04-28 11:38 UTC, schnek commented
> I can't reproduce

not on latest version (git not upd)

2022-04-28 14:45 UTC, schnek commented
![image](https://user-images.githubusercontent.com/1216225/165776626-c223a17f-52c1-4d82-bb38-eb3368d874df.png)

![image](https://user-images.githubusercontent.com/1216225/165776688-c76fd206-acf8-446b-a6f2-24bc5263a2e4.png)

test for 3.3.5 crasch Eye of the Storm test( 1x1)

2022-04-28 21:05 UTC, aaron02 commented
> 

should now be working

2022-04-29 08:56 UTC, schnek commented
![image](https://user-images.githubusercontent.com/1216225/165913596-b4011706-239b-4317-bf6f-e2daaac5e017.png)
test for 3.3.5 crasch Warsong Gulch test( 1x1)
![image](https://user-images.githubusercontent.com/1216225/165913880-9f2c066d-5ad4-43ec-8944-b89947cf3ce9.png)
transfer to bg and wait for the gate to open, a crash will occur...

2022-04-29 17:06 UTC, aaron02 commented
how did u trigger the second crash?

2022-04-29 17:14 UTC, schnek commented
> how did u trigger the second crash? first one should be fixed

moving along the route and taking flags along the way.
now again rebuild and testing.

2022-04-29 21:09 UTC, schnek commented
![image](https://user-images.githubusercontent.com/1216225/166068897-c27c2905-6729-4947-bfca-2564f7eaf2b7.png)
also happens random crash on bg after some time (Arathi Basin)

2022-05-01 04:43 UTC, schnek commented
![image](https://user-images.githubusercontent.com/1216225/166132440-c43b56c4-4a7d-4199-a5c9-ddc0f103ea7a.png)
the grid on the vehicle was incorrect for 2 players.

2022-05-01 09:22 UTC, aaron02 commented
this is not related to this pr, this is a movement packet issue

2022-05-03 16:41 UTC, schnek commented
in a taxi after meeting at the destination, the player does not leave the mount
client crash when re-entering the game
![image](https://user-images.githubusercontent.com/1216225/166499866-cb9bbdf4-c58f-4762-b705-e51ec14601fe.png)

2022-05-03 17:44 UTC, Appled commented
> in a taxi after meeting at the destination, the player does not leave the mount client crash when re-entering the game ![image](https://user-images.githubusercontent.com/1216225/166499866-cb9bbdf4-c58f-4762-b705-e51ec14601fe.png)

Not related to this pr

2022-05-05 18:57 UTC, schnek commented
if you kill an npc for example frostbolt then he will return to his place (example below)
![image](https://user-images.githubusercontent.com/1216225/167004398-056aa40f-5524-4209-9b72-2615454233eb.png)

if you apply the command (kill) everything is fine
![image](https://user-images.githubusercontent.com/1216225/167004448-7794f24b-8a90-4408-aa56-8c1af7325158.png)

2022-05-05 19:08 UTC, schnek commented
on battlefields: all battlefields go for about ~5 minutes and disconnect. maybe it's because of 1x1

2022-05-05 19:20 UTC, schnek commented
> your issue with the npcs i am not able to reproduce tried serveral ways npc kepps the position where i killed it, no returning to his place

i use 3.3.5 (if that's the case then that's good)

2022-05-05 19:23 UTC, aaron02 commented
> > your issue with the npcs i am not able to reproduce tried serveral ways npc kepps the position where i killed it, no returning to his place
> 
> i use 3.3.5 (if that's the case then that's good)

i also use 3.3.5 :)

2022-05-05 19:46 UTC, aaron02 commented
> on battlefields: all battlefields go for about ~5 minutes and disconnect. maybe it's because of 1x1

fixed now, i dont stopped map unload when player entered bg ^^

2022-05-05 22:34 UTC, schnek commented
if you enter in bg and exit before urgent
![image](https://user-images.githubusercontent.com/1216225/167035884-00824bc2-1c2f-495f-a094-174a9e0a12d4.png)

2022-05-06 17:36 UTC, Appled commented
> if you enter in bg and exit before urgent ![image](https://user-images.githubusercontent.com/1216225/167035884-00824bc2-1c2f-495f-a094-174a9e0a12d4.png)

Try again

2022-05-06 18:18 UTC, schnek commented
> Try again

fixed 👍

2022-05-06 20:39 UTC, aaron02 commented
rdy now @Zyres

2022-05-07 07:06 UTC, Zyres commented
@aaron02 okay diving into it :-)

2022-05-08 03:56 UTC, Appled requested changes

2022-05-08 03:56 UTC, Appled commented on src/world/Server/Script/ScriptMgr.cpp
> +        uint32 buff;
uint32_t

2022-05-08 03:56 UTC, Appled commented on src/world/Server/Script/ScriptMgr.h
> +        InstanceMap* GetInstance() { return mInstance->getInstance(); }
Functions should start with lowercase

2022-05-08 03:56 UTC, Appled commented on src/world/Storage/MySQLDataStore.cpp
> +    uint32_t entrance_map = uint32_t(mapEntry->parent_map);
Use static_cast instead of C style cast

2022-05-08 03:56 UTC, Appled commented on src/world/Storage/MySQLDataStore.cpp
> +    uint32_t entrance_map = uint32_t(mapEntry->repopmapid);
Use static_cast instead of C style cast

2022-05-08 09:40 UTC, aaron02 commented on src/scripts/InstanceScripts/Tbc/Raid_Magtheridons_Lair.cpp
> +        if (GetWorldMap()->isUnloadPending())
no longer needed, i added this in the other threading to prevent a crash, now i delete the line its no longer needed

2022-05-08 12:43 UTC, aaron02 commented on src/world/Objects/Units/Creatures/Creature.cpp
> +        Unit::setDeathState(CORPSE);
this is intended

2022-05-08 12:44 UTC, aaron02 commented on src/world/Objects/Units/Creatures/Creature.cpp
> +    if (true)
the function below is prepared for when respawns are handled fully to dont use object casts

2022-05-08 13:14 UTC, Zyres commented
Non PCH build is broken

2022-05-09 02:15 UTC, Appled requested changes

2022-05-09 02:15 UTC, Appled commented on src/world/Map/Maps/WorldMap.cpp
> +    case HighGuid::GameObject:
Indent cases in switch statement

2022-05-09 02:15 UTC, Appled commented on src/world/Map/Maps/WorldMap.cpp
> +    case SPAWN_TYPE_CREATURE:
Indent cases in switch statement

2022-05-09 02:15 UTC, Appled commented on src/world/Map/Maps/WorldMap.cpp
> +    case SPAWN_TYPE_CREATURE:
Indent cases in switch statement

2022-05-09 02:15 UTC, Appled commented on src/world/Map/Maps/WorldMap.cpp
> +            sLogger.failure("Invalid spawn type %u (spawnid %u) on map %u", static_cast<uint32>(type), spawnId, getBaseMap()->getMapId());
uint32_t

2022-05-09 02:15 UTC, Appled commented on src/world/Map/Maps/WorldMap.hpp
> +    void getZoneAndAreaId(uint32_t phaseMask, uint32_t& zoneid, uint32_t& areaid, LocationVector const& pos) { getZoneAndAreaId(phaseMask, zoneid, areaid, pos.getPositionX(), pos.getPositionY(), pos.
Make only one function for getZoneAndAreaId with LocationVector as parameter

2022-05-09 02:15 UTC, Appled commented on src/world/Map/Maps/WorldMap.hpp
> +    float getHeight(LocationVector const& pos, bool vmap = true, float maxSearchDist = 50.0f) const { return getHeight(pos.getPositionX(), pos.getPositionY(), pos.getPositionZ(), vmap, maxSearchDist)
Make only one function for getHeight with LocationVector as function parameter

2022-05-09 02:15 UTC, Appled commented on src/world/Map/Maps/WorldMap.hpp
> +    float getHeight(uint32_t phasemask, LocationVector const& pos, bool vmap = true, float maxSearchDist = 50.0f) const { return getHeight(phasemask, pos.getPositionX(), pos.getPositionY(), pos.getPo
Make only one function for getHeight with LocationVector as function parameter

2022-05-09 02:15 UTC, Appled commented on src/world/Map/Maps/WorldMap.hpp
> +    GameObject* createAndSpawnGameObject(uint32_t entryID, float x, float y, float z, float o, float scale);
Use LocationVector instead of xyzo in function parameters

2022-05-09 02:15 UTC, Appled commented on src/scripts/MiscScripts/GameObjects.cpp
> +        Creature* shaghostspawn = player->getWorldMap()->createAndSpawnCreature(9136, pos);
You removed a nullptr check here

2022-05-09 21:56 UTC, Appled approved these changes
@Zyres please do not forget to squash commits XD

2022-05-10 15:28 UTC, Zyres commented
> @Zyres please do not forget to squash commits XD

I will squash them :-)

2022-05-10 15:38 UTC, aaron02 commented
> So, we change how we load cells/maps, what about #22 and #404?

still now realy working how it should. More Cell rework will follow also with some flags in adition for large mapwide npcs. This Pr got realy large now^^

2022-05-10 15:58 UTC, merged