Gameobjects
AscEmu/AscEmu pull request #1035
Opened 2022-06-09 11:14 UTC by aaron02

**Description**
Clean Up Gameobjects, use proper Loot States, Proper Open Closed Handling and Changed Respawn and Despawn Handling

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [x] Build AE.
- [x] Server startup.
- [x] Log into world.

**Multiversion Ingame Tests Performed:**
- [x] WotLK

2022-06-13 16:45 UTC, Zyres commented
Update sql updatefiles.

2022-06-14 01:36 UTC, Appled requested changes

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +            uint32 conditionID1;                //10
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +            uint32 conditionID1;                // parameter_6
uint32_t int32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +            uint32 closeTextID;                 // parameter_7
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +            uint32 charges;                                 //1
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +            uint32 conditionID1;                // parameter_8
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +            uint32 openTextID;                  // parameter_4
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +            uint32 unidirectional;              // parameter_21
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +    void setSpellId(uint32 id)
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +        void removeLootMode(uint16 lootMode) { m_LootMode &= ~lootMode; }
uint16_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/GameObject.h
> +        bool IsLootable() { return true; }
Functions should start with lowercase character

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/Transporter.cpp
> +    setGoType(static_cast<uint8>(gameobject_properties->type));
uint8_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/Units/Unit.cpp
> +    for (uint8 i = 0; i < 4; ++i)
uint8_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/Units/Unit.cpp
> +    if (uint32 spellid = gameObj->getSpellId())
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/Units/Unit.cpp
> +void Unit::removeGameObject(uint32 spellid, bool del)
uint32_t

2022-06-14 01:36 UTC, Appled commented on src/world/Objects/Units/Unit.cpp
> +            ++next;
Use braces around else statement if you used them in if statement

2022-06-14 01:36 UTC, Appled commented on src/world/Server/Packets/Handlers/LootHandler.cpp
> +                    go->setLootState(GO_JUST_DEACTIVATED);
Use braces around else statement if you used them in if statement

2022-06-14 01:36 UTC, Appled commented on src/world/Spell/SpellEffects.Legacy.cpp
> +    int32_t duration = ::GetDuration(sSpellDurationStore.LookupEntry(m_spellInfo->getDurationIndex()));
Use Spell::getDuration() instead

2022-06-14 19:40 UTC, Appled commented on src/world/Objects/GameObject.h
> +        bool IsLootable() { return true; }
Then you should define it with override 😉

2022-06-15 20:46 UTC, Appled approved these changes

2022-06-17 19:08 UTC, aaron02 commented
@Zyres should be rdy and sql updated to match all new sql updates

2022-06-29 07:41 UTC, Zyres requested changes

2022-06-29 07:41 UTC, Zyres commented on src/world/Chat/Commands/GameObjectCommands.cpp
> +            WorldDatabase.Execute("REPLACE INTO gameobject_spawns_overrides VALUES(%u, %u, %u, %3.3lf,%u,%u)", go_spawn->id, VERSION_STRING, VERSION_STRING, gameobject->getScale(), go_faction, gameob
This is not the same as the "old" UPDATE.....
You try to REPLACE data with id, VERSION, VERSION... but most spawns are multiversion means: id, VERSION-1, VERSION-2.

2022-06-29 07:41 UTC, Zyres commented on src/world/Chat/Commands/GameObjectCommands.cpp
> +            WorldDatabase.Execute("REPLACE INTO gameobject_spawns_overrides VALUES(%u, %u, %u, %3.3lf,%u,%u)", go_spawn->id, VERSION_STRING, VERSION_STRING, gameobject->getScale(), gameobject->getFac
Same as before, REPLACE is wrong e.g. does not replace anything for multiversion spawns.

2022-06-29 07:41 UTC, Zyres commented on src/world/Chat/Commands/GameObjectCommands.cpp
> +            WorldDatabase.Execute("REPLACE INTO gameobject_spawns_overrides VALUES(%u, %u, %u, %3.3lf,%u,%u)", go_spawn->id, VERSION_STRING, VERSION_STRING, scale, gameobject->getFactionTemplate(), g
Same....

2022-06-29 07:41 UTC, Zyres commented on src/world/Objects/GameObject.cpp
> +void GameObject::saveToDB()
That function is kind of odd.
If it is a new spawn, save the data with the current Version. If the spawn is already in gameobject_spawns just update the data and keep min/max_build as it was...

2022-06-29 08:32 UTC, Zyres commented
The wiki should be updated.

2022-07-04 06:05 UTC, merged