Rewrite of the Logging
AscEmu/AscEmu pull request #865
Opened 2021-05-07 11:04 UTC by Adrian-Weihs

**Description**
Rewrite of the Logging in AscEmu, the methods have been built to be similar to apach's log4j. The name Logger is a much better name for Logging than Log. Also a log message have now a Severity (Info, Warning, Failure, Fatal) and a MessageType (Trace, Debug, Minor, Major). The configuration for logon and world changed. Some errors which will crash/close the server are now Fatal Messages.

**Todo / Checklist**
- [X] Target is branch develop.
- [X] Detailed description about this pull request.
- [X] Checked AE-Coding standards.

**Tests Performed:** 
- [X] Build AE.
- [X] Server startup.
- [] Log into world.

2021-05-07 12:07 UTC, schnek commented
1. resources.aps wtf?
![image](https://user-images.githubusercontent.com/1216225/117446783-44fd7e80-af45-11eb-835d-5534a755080e.png)
2. LOGGER.debug -> logger.debug i would change case
3. has the work become faster?🤔

2021-05-07 12:16 UTC, Adrian-Weihs commented
> 
> 
>     1. resources.aps wtf?
>        ![image](https://user-images.githubusercontent.com/1216225/117446783-44fd7e80-af45-11eb-835d-5534a755080e.png)
> 
>     2. LOGGER.debug -> logger.debug i would change case
> 
>     3. has the work become faster?🤔

1. Ups shouldn't pushed it
2. mhh its a define? I come mainly from JAVA so there we write final static variables upper case
3. u mean "faster" performance whise? i dont think so it should be the same but its more clear now

2021-05-07 12:31 UTC, Adrian-Weihs commented
ok i messed up

2021-05-07 12:31 UTC, schnek commented
> mhh its a define? I come mainly from JAVA so there we write final static variables upper case

yes
`#define logger AscEmu::Logging::Logger::getInstance()`

> u mean "faster" performance whise? i dont think so it should be the same but its more clear now

ok, I'll take a look

2021-05-07 12:50 UTC, Zyres commented
Hey Adrian 😘 nice to See something from you, how ist it going?

2021-05-07 13:33 UTC, schnek commented
Renamed logger to AElogger.
Renamed LOGGER to logger.

2021-05-07 14:29 UTC, Adrian-Weihs commented
> 
> 
> Hey Adrian 😘 nice to See something from you, how ist it going?

Hey :-* I'm fine and u? If u want we can make a discord call tonight.

2021-05-07 15:21 UTC, Appled commented
Thank you for your PR 😃 
I would rename "logger" to "sLogger" because most of our Singleton classes use that kind of definition. Personally, I would also rename following functions under Logger class: 'debug' to 'writeDebug', 'trace' to 'writeTrace', 'fatal' to 'writeFatal' etc etc, to keep better clarity what the functions are doing, but I let @Zyres decide on that.

I will do a proper review when the build is fixed 😃

2021-05-07 15:32 UTC, schnek commented
logger.debug looks much better than logger.writeDebug it seems to me. The only thing is that the console is now black and white and looks boring.

![image](https://user-images.githubusercontent.com/1216225/117473053-3a051700-af62-11eb-89ac-63b0354d7801.png)
as an option additionally make color...

2021-05-07 17:04 UTC, Adrian-Weihs commented
Yeah will rename it to sLogger, but i would say i will stay with debug() etc as method names. I will add a log method where u can set the color

2021-05-07 20:01 UTC, Appled requested changes
It's good, just couple codestyle issues.
Also, update the "last edited" on both config files.

2021-05-08 19:31 UTC, Adrian-Weihs commented on src/shared/CMakeLists.txt
> +	Logging/Logger.cpp
done

2021-05-08 19:31 UTC, Adrian-Weihs commented on src/shared/CMakeLists.txt
> +	Logging/Severity.hpp
done

2021-05-08 19:31 UTC, Adrian-Weihs commented on src/shared/LogDefines.hpp
> +
done

2021-05-08 19:32 UTC, Adrian-Weihs commented on src/shared/Logging/Logger.hpp
> +        void finalize()
done

2021-05-08 19:32 UTC, Adrian-Weihs commented on src/shared/Logging/Logger.hpp
> +
done

2021-05-09 01:08 UTC, Appled approved these changes
👍

2021-05-09 08:12 UTC, merged