Rewrite/encapsulate RealmManager.
AscEmu/AscEmu pull request #872
Opened 2021-05-12 21:13 UTC by Adrian-Weihs

**Description**
The old RealmsMgr was rewritten into RealmManager and is now in the namespace AscEmu::Realm. The whole logging edited. Every variable is now private. The Method updateRealmPop renamed into setRealmPopulation.

**Todo / Checklist**
- [X] Target is branch develop.
- [X] Detailed description about this pull request.
- [X] Checked AE-Coding standards.

**Tests Performed:** 
- [X] Build AE.
- [X] Server startup.
- [X] Log into world.

2021-05-12 23:59 UTC, Appled requested changes

2021-05-12 23:59 UTC, Appled commented on src/logonserver/Realm/RealmManager.hpp
> +        void addServerSocket(::LogonCommServerSocket* sock)
Define functions in cpp files

2021-05-12 23:59 UTC, Appled commented on src/logonserver/Realm/RealmManager.hpp
> +        void removeServerSocket(::LogonCommServerSocket* sock)
Define functions in cpp files

2021-05-13 09:00 UTC, Adrian-Weihs commented on src/logonserver/Realm/RealmManager.hpp
> +        void addServerSocket(::LogonCommServerSocket* sock)
done

2021-05-13 09:00 UTC, Adrian-Weihs commented on src/logonserver/Realm/RealmManager.hpp
> +        void removeServerSocket(::LogonCommServerSocket* sock)
done

2021-05-13 11:44 UTC, merged