Do Place spaces between control statements and their parentheses.
AscEmu/AscEmu pull request #950
Opened 2021-11-01 20:01 UTC by schnek

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [x] Build AE.
- [x] Server startup.
- [x] Log into world.

**Multiversion Ingame Tests Performed:**
- [x] BC
- [x] WotLK
- [x] Cata

clean cmake cache and rebuild the source files

2021-11-02 07:23 UTC, Zyres requested changes
Please check out the missing spaces for elseif too.
Take your time, we should solve the missing spaces in one PR

2021-11-02 07:23 UTC, Zyres commented on CMakeLists.txt
>      elseif(APPLE)
Missing

2021-11-02 07:23 UTC, Zyres commented on cmake/CheckSystem.cmake
>  elseif(UNIX)
Missing

2021-11-02 07:23 UTC, Zyres commented on cmake/CheckSystem.cmake
>      elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD" OR CMAKE_SYSTEM_NAME STREQUAL "kFreeBSD")
Missing

2021-11-02 07:23 UTC, Zyres commented on cmake/Systems/Apple.cmake
>  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
Missing

2021-11-02 07:23 UTC, Zyres commented on cmake/Systems/Linux.cmake
>  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
Missing

2021-11-02 07:23 UTC, Zyres commented on dep/CMakeLists.txt
>      if("${ASCEMU_VERSION}" STREQUAL "Cata" OR "${ASCEMU_VERSION}" STREQUAL "Mop")
Missing

2021-11-02 07:23 UTC, Zyres commented on src/scripts/ExtraScripts/CMakeLists.txt
>  endif(NOT BUILD_EXTRASCRIPTS)
Missing

2021-11-02 07:23 UTC, Zyres commented on src/scripts/GossipScripts/CMakeLists.txt
>  endif(NOT BUILD_GOSSIPSCRIPTS)
Missing

2021-11-02 07:23 UTC, Zyres commented on src/shared/Network/CMakeLists.txt
>  elseif((CMAKE_SYSTEM_NAME STREQUAL "FreeBSD" OR CMAKE_SYSTEM_NAME STREQUAL "kFreeBSD") OR APPLE)
Missing

2021-11-02 07:23 UTC, Zyres commented on src/tools/CMakeLists.txt
>     if("${ASCEMU_VERSION}" STREQUAL "WotLK" OR "${ASCEMU_VERSION}" STREQUAL "TBC" OR "${ASCEMU_VERSION}" STREQUAL "Classic")
Missing

2021-11-03 07:45 UTC, Zyres requested changes
Hey :-) Please apply the rule to all controle statements (if, elseif, else, endif) otherwise we have to touch these files again.

2021-11-03 07:45 UTC, Zyres commented on CMakeLists.txt
>      else()
now else is also missing....

2021-11-03 07:45 UTC, Zyres commented on cmake/CheckSystem.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/CheckSystem.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/CheckSystem.cmake
>      else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Compilers/clang.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Compilers/gcc.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Compilers/msvc.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindMySQL.cmake
> +else()
removed, why?

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindMySQL.cmake
> +else()
removed why?

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindMySQL.cmake
> +else(WIN32)
removed why

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindMySQL.cmake
> +    else(MYSQL_INCLUDE_DIR)
removed why?

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindMySQL.cmake
> +else(MYSQL_LIBRARY)
removed why?

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
>    else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
>    else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
> +else()
removed why?

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
> +    else()
removed why?

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
>      else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
>      else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
> +  else()
removed why?

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
>      else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
>      else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindOpenSSL.cmake
>    else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Modules/FindPCRE.cmake
> +else(PCRE_FOUND)
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Systems/Apple.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Systems/FreeBSD.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Systems/Linux.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on cmake/Systems/Windows.cmake
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on dep/CMakeLists.txt
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on dep/CMakeLists.txt
>      else()
missing

2021-11-03 07:45 UTC, Zyres commented on src/scripts/InstanceScripts/Cata/CMakeLists.txt
>  unset(PATH_PREFIX)
missing new line

2021-11-03 07:45 UTC, Zyres commented on src/shared/Network/CMakeLists.txt
>  else()
missing

2021-11-03 07:45 UTC, Zyres commented on src/tools/CMakeLists.txt
> +    else()
missing

2021-11-03 07:45 UTC, Zyres commented on src/tools/CMakeLists.txt
>  else()
missing

2021-11-03 20:02 UTC, schnek commented on cmake/Modules/FindMySQL.cmake
> +else()
i updated) there was a problem in git

2021-11-04 18:50 UTC, merged