cata reforging
AscEmu/AscEmu pull request #971
Opened 2021-11-23 11:57 UTC by aaron02

**Description**
Activated reforging in cata and optimized transmog visual in character screen

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [x] Build AE.
- [x] Server startup.
- [x] Log into world.

***Multiversion Ingame Tests Performed:***
- [x] BC
- [x] WotLK
- [x] Cata

2021-11-23 15:50 UTC, Appled requested changes

2021-11-23 15:50 UTC, Appled commented on src/world/Management/Item.cpp
> +                for (uint32_t f = 0; f < MAX_ITEM_ENCHANTMENT_EFFECTS; ++f)
You can replace uint32_t with uint8_t here

2021-11-23 15:50 UTC, Appled commented on src/world/Management/Item.cpp
> +                for (uint32_t f = 0; f < MAX_ITEM_ENCHANTMENT_EFFECTS; ++f)
You can replace uint32_t with uint8_t here

2021-11-23 15:50 UTC, Appled commented on src/world/Management/Item.cpp
> +                        for (int k = 0; k < MAX_ITEM_ENCHANTMENT_EFFECTS; ++k)
You can replace int with uint8_t here

2021-11-23 15:50 UTC, Appled commented on src/world/Units/Players/PlayerDefines.hpp
> +    CR_RESILIENCE_PLAYER_DAMAGE_TAKEN   = 15,
This is no longer correct for versions < Cata (should be ranged crit resilience)

2021-11-23 15:50 UTC, Appled commented on src/world/Units/Players/PlayerDefines.hpp
> +    CR_RESILIENCE_CRIT_TAKEN            = 14,
This is no longer correct for versions < Cata (should be melee crit resilience)

2021-11-23 17:24 UTC, aaron02 commented on src/world/GameCata/Storage/DBCStructures.h
> +        uint32_t spells[MAX_ITEM_ENCHANTMENT_EFFECTS];                                         // 2-6 enchant_id
the other colums are always empty.  there are always no more than 3 enchatns available on an item

2021-11-24 00:51 UTC, Appled requested changes

2021-11-24 00:51 UTC, Appled commented on src/world/Units/Players/Player.cpp
> +    for (uint8 i = 0; i < VOID_STORAGE_MAX_SLOT; ++i)
uint8_t

2021-11-24 00:51 UTC, Appled commented on src/world/Server/Packets/Handlers/VoidStorageHandler.cpp
> +    bool usedSrcSlot = player->getVoidStorageItem(oldSlot) != NULL; // should be always true
Do not use NULL, always nullptr

2021-11-24 00:51 UTC, Appled commented on src/world/Server/Packets/Handlers/VoidStorageHandler.cpp
> +    bool usedDestSlot = player->getVoidStorageItem(newSlot) != NULL;
Do not use NULL, always nullptr

2021-11-24 00:51 UTC, Appled commented on src/world/Units/Players/Player.cpp
> +uint8 Player::getNumOfVoidStorageFreeSlots() const
uint8_t

2021-11-24 00:51 UTC, Appled commented on src/world/Units/Players/Player.cpp
> +    _voidStorageItems[slot] = NULL;
Do not use NULL, always nullptr

2021-11-24 00:51 UTC, Appled commented on src/world/Units/Players/Player.cpp
> +        return NULL;
Do not use NULL, always nullptr

2021-11-24 00:51 UTC, Appled commented on src/world/Units/Players/Player.cpp
> +    return NULL;
Do not use NULL, always nullptr

2021-11-24 13:50 UTC, Appled approved these changes

2021-11-25 17:11 UTC, merged